name = "my-app"
compatibility_date = "2024-12-30"
assets = { binding = "ASSETS", directory = "apps/docs/.open-next/assets" }
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = "apps/docs/.open-next/"